<?php

namespace App\Connector\Components\AI\Prompts\Instructions\Amazon;

class MapCategories
{

    public  $mapping = [
        // clothing
        "clothing_accessories" => "clothing",
        'clothing_and_accessories' => "clothing",
        'Clothing' => "clothing",
        'clothing' => "clothing",
        'Clothing & Accessories' => "clothing",
        'clothing_luggage_travel' => "clothing",
        'clothes' => "clothing",
        'shoes_handbags_and_sunglasses' => "clothing",
        'shoes_handbags' => "clothing",
        'apparell' => "clothing",
        'shoes_and_accessories' => "clothing",
        'shoes_accessories' => "clothing",
        'shoes' => "clothing",
        'Shoes & Bags' => "clothing",
        'sunglasses_and_fashion_eyewear' => "clothing",
        'apparel' => "clothing",
        'Shoes' => "clothing",
        'Shoes and accessories' => "clothing",
        'luggage' => "clothing",
        'luggage_and_travel_accessories' => "clothing",
        'Luggage' => "clothing",
        'shoe_handbags' => "clothing",
        'luggage_and_bags' => "clothing",
        'MotoApparel' => "clothing",
        'sunglasses' => "clothing",
        // beauty
        'beauty' => "beauty",
        'Beauty' => "beauty",
        'health_personal_care' => "beauty",
        'health_and_personalcare' => "beauty",
        'Health and personal care' => 'beauty',
        'Health' => "beauty",
        'biss_professional_health_care' => "beauty",
        'health' => "beauty",
        'professional_healthcare' => "beauty",
        'personal_healthcare' => "beauty",
        'biss_professional_health_care' => "beauty",

        // toys
        'toys_and_games' => "toys",
        'toys' => "toys",
        'toys_baby' => "toys",
        'ToysBaby' => "toys",
        'Toys' => "toys",

        //  sports
        'sports' => "sports",
        'Sports' => "sports",
        'sports_equipments' => "sports",
        'sports_excercise_and_fitness' => "sports",
        'sports_and_outdoors' => "sports",
        'Sporting Goods' => "sports",
        'outdoor_equipments' => "sports",
        'outdoors' => "sports",
        'Outdoors' => "sports",
        'sport' => "sports",
        'Sport' => "sports",


        // pet supplies
        'pet_supplies' => "pet",
        'PetSupplies' => "pet",
        'PetSupplies' => "pet",
        'pet_products' => "pet",

        // automotive
        'automotive_powersports_parts_accessories' => "automotive",
        'car_and_motorbikes' => "automotive",
        'automotive' => "automotive",
        'Automotive' => "automotive",
        'automotive_parts_and_accessories' => "automotive",
        'tires_wheels' => "automotive",
        'AutoAccessory' => "automotive",
        'auto_accessories' => "automotive",
        'car_motorbike_parts' => "automotive",
        'car_motobike' => "automotive",
        'Auto & Motorcycle Parts & Accessories' => 'automotive',

        // electronics
        "Computers" => "electronics",
        "cellphones_accessories_wireless" => "electronics",
        "consumer_electronics" => "electronics",
        "electronics_accessories_devices" => "electronics",
        "major_appliances" => "electronics",
        "computer_software" => "electronics",
        "electronics_pc" => "electronics",
        "camera_photo" => "electronics",
        "video_games_console" => "electronics",
        "Consumer electronics" => "electronics",
        "personal_care_appliances" => "electronics",
        "major_appliances" => "electronics",
        "Computers & Accessories" => "electronics",
        "personal_computer" => "electronics",
        "SoftwareVideoGames" => "electronics",
        "electronics_pc" => "electronics",
        "electronics_mobile_phones_accessories" => "electronics",
        "computer_accessories" => "electronics",
        "ConsumerElectronics" => "electronics",
        "software_and_videogames" => "electronics",
        "video_games_games" => "electronics",
        "large_appliances" => "electronics",
        "camera" => "electronics",
        "computer_software" => "electronics",
        "computer_accessories" => "electronics",
        "VideoGames" => "electronics",
        "software" => "electronics",
        "camera_and_photo" => "electronics",
        "Wireless" => "electronics",

        // "=>"industrial",
        "Industrial" => "industrial",
        "industrial_scientific_industrial_other" => "industrial",
        "industrial_and_scientific_industrial_file" => "industrial",
        "industrial" => "industrial",
        "industrial_scientific_lab_scientific_supplies" => "industrial",
        "industrial_and_scientific_professional_healthcare" => "industrial",
        "biss_industrial" => "industrial",
        "tools_and_building_supplies" => "industrial",
        "lab_supply" => "industrial",
        "industrial_scientific_raw_materials" => "industrial",
        "labsupplies" => "industrial",
        "industrial_and_scientific_food_service" => "industrial",

        // "=>"office",
        "office_products" => "office",
        "office" => "office",
        "Office Products" => "office",
        "office_product" => "office",
        "Office" => "office",
        "musical_instruments" => "office",
        "Musical instruments" => "office",


        // "=>"food",
        "grocery_gourmet_food" => "food",
        "pantry_food_drinks" => "food",
        "biss_food_services" => "food",
        "foods_and_beverages" => "food",
        "bear_wine_spirits" => "food",
        "foods_beverages" => "food",
        "FoodAndBeverages" => "food",
        "grocery" => "food",
        "alcoholic_beverages" => "food",
        "Foods and drinks" => "food",
        "FoodServiceAndJanSan" => "food",
        "grocery_and_gourmet" => "food",
        "food_and_beverages" => "food",


        // baby
        "baby" => "food",
        // eyewear
        "eyewear" => "eyewear",

        // 'jewellery',
        'jewellery' => 'jewellery',
        'jwellery' => 'jewellery',
        'Jewellery' => 'jewellery',
        'Jewelry' => 'jewellery',
        'jewelry' => 'jewellery',

        // "=>"home",
        "home_homedecor_kitchen_garden_furniture" => "home",
        "home_homedecor_kitchen_garden_furniture" => "home",
        "home" => "home",
        "home_kitchen" => "home",
        "tools_and_home_improvement" => "home",
        "home_improvement" => "home",
        "handmade" => "home",
        "homeware_living_decoratins" => "home",
        "tools_home_improvement" => "home",
        "kitchen" => "home",
        "home_garden" => "home",
        "kitnchen_household" => "home",
        "Home" => "home",
        "home_other" => "home",
        "tools_home_improvement" => "home",
        "lawn_garden" => "home",
        "LawnAndGarden" => "home",
        "garden" => "home",
        "home_other" => "home",
        "kitnchen_household" => "home",
        "home and home appliances" => "home",
        "Small household appliances (kitchen)" => "home",
        "law_and_garden" => "home",
        "law_garden" => "home",
        "Kitchen" => "home",
        "home_and_kitchen_lightning" => "home",
        "Lawn and garden" => "home",
        "Lawn & Garden" => "home",
        "homeimprovement" => "home",
        "Home Improvement" => "home",
        "living" => "home",
        "lightning" => "home",
        "Lighting" => "home",
        "lighting" => "home",


        // watches
        "watches" => "watch",
        "Watches" => "watch",

        // books
        "books" => "books",
        "book" => "books",
        "Book Loader" => "books",
        "Bookloader" => "books",

        // entertainment
        "entertainment_collectibles" => "entertainment",

        //test
        "default"=>"default"
    ];
}
