<h3 class='text-center mt-5 mb-2 text-white'>Create App Subscription Form</h3>
<div class='d-flex justify-content-center align-items-center'>

    <form class="rounded w-50 p-2 shadow" action="" method="POST" style="background-color:#495C83">
        <div class="form-group pr-3 pl-3 pt-2">
            <label for="" class="text-light">Event Code</label>
            <input type="text" class="form-control" id="" placeholder="Event Code ex:product/create" name="event_code" required>
        </div>

        <div class="form-group pr-3 pl-3 pt-2">
            <label for="" class="text-light">Event Handler Id</label>
            <input type="text" class="form-control" id="" placeholder="Event Handler Id" name="event_handler_id" required>
        </div>

        <div class="form-group pr-3 pl-3 pt-2 ">
            <label for="" class="text-light">Queue Data</label>
        </div>

        <div class='card pr-3 pl-3 pt-2 mt-1 mr-3 ml-3' style="background-color:#7A86B6">

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">Type</label>
                <input type="text" class="form-control" id="" placeholder="Type" name="queue_data[type]" required>
            </div>

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">Class Name</label>
                <input type="text" class="form-control" id="" placeholder="Class Name" name="queue_data[class_name]" required>
            </div>

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">Method</label>
                <input type="text" class="form-control" id="" placeholder="Method name" name="queue_data[method]" required>
            </div>

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">Action</label>
                <input type="text" class="form-control" id="" placeholder="Action" name="queue_data[action]" required>
            </div>

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">Queue Name</label>
                <input type="text" class="form-control" id="" placeholder="Queue Name" name="queue_data[queue_name]" required>
            </div>

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">App Code</label>
                <input type="text" class="form-control" id="" placeholder="App Code" name="queue_data[app_code]" required>
            </div>

            <div class="form-group pr-3 pl-3 pt-2">
                <label for="">MarketPlace</label>
                <input type="text" class="form-control" id="" placeholder="App Code" name="queue_data[marketplace]" required>
            </div>

        </div>

        <div class="form-group pr-3 pl-3 pt-2 pb-2">
            <button type="submit" class="btn rounded" style="background-color:#FBB454">Create Subscription</button>
        </div>

    </form>
</div>